name: qode
channels:
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pytorch=1.10.0
  - torchvision=0.11.1
  - fvcore=0.1.5
  - iopath=0.1.9
  - matplotlib=3.5.0
  - pandas=1.3.5
  - pytest=6.2.5
  - torchdiffeq
  - qutip
  - scikit-learn
  - imageio
